chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_msg/', views.get_msg, name='get_msg'),
    path('get_group_msg/', views.get_group_msg, name='get_group_msg'),
    path('block', views.block_friend, name='block_friend'),
    path('search_people', views.search_people, name='search_people'),
    # path('add_msg', views.add_msg, name='add_msg')

    path('profile', views.profile, name='profile'),
    path('about', views.About.as_view()),
]

mychat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('chat/', include('chat.urls')),
    path('', RedirectView.as_view(url='chat')),

    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register', views.register_form, name='register_form'),
    path('adduser', views.adduser, name='adduser'),
    path('login', views.login_form, name='login_form'),
    path('auth_user', views.auth_user, name='auth_user'),
    path('logout', views.logout_form, name='logout_form'),
]

users/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User


class SiteUser(models.Model):
    user = models.OneToOneField(User, null=False, blank=False, on_delete=models.CASCADE, related_name='siteuser')
    last_seen = models.DateTimeField(auto_now_add=True)
    is_online = models.BooleanField(default=False)
    is_private = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = []

    def __str__(self):
        return self.user.username

class FriendList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='fl_u')
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name='fl_f')
    room_id = models.ForeignKey('Room', on_delete=models.CASCADE, related_name='fl_room_id')
    had_blocked = models.BooleanField(default=False)
    insert_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class FriendRequest(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='req_from')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='req_to')
    send_date = models.DateTimeField(auto_now_add=True)
    reaction_date = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(null=True)

    def __str__(self):
        return self.from_user.username


class Room(models.Model):
    room_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    insert_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.room_id}'

users/forms.py
from django.contrib.auth.models import User
from django import forms

class SiteUserLoginForm(forms.Form):
    username = forms.CharField(label='Username',
                               widget=forms.TextInput(attrs={
                                                'class': 'form-control',
                                                'name': 'username',
                                                'placeholder': 'Enter Username',
                                                'autofocus': "autofocus"
                                            })
                               )
    password = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                    'name': 'password',
                                    'placeholder': 'Enter Password'
                                }))
    class Meta:
        model = User
        # fields = ['username', 'password']
        #
        # widgets = {
        #     'username': TextInput(attrs={
        #         'class': 'form-control',
        #         'name': 'username',
        #         'placeholder': 'Enter Username'
        #     }),
        #     'password': PasswordInput(attrs={
        #         'class': 'form-control',
        #         'name': 'password',
        #         'placeholder': 'Enter Password'
        #     }),
        # }

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from .forms import SiteUserLoginForm
from django.contrib.auth.models import User
from .models import SiteUser

from django.contrib.auth import authenticate, login, logout

def register_form(request):
    form = UserCreationForm()
    data = {
        'form':form
    }
    return render(request, 'users/register.html', data)

def adduser(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = User.objects.order_by('-id')[:1][0]
            last_user = User.objects.get(id=user.id)
            siteuser = SiteUser()
            siteuser.user = last_user
            siteuser.save()
            return redirect('users:login_form')
        else:
            return render(request, 'users/error.html', {'error':'Form is not Valid'})

    else:
        return render(request, 'users/error.html', {'error':'Request method error'})

def login_form(request):
    if request.user.is_authenticated:
        return redirect('chat:index')

    form = SiteUserLoginForm()
    data = {
        'form':form,
        'errors':''
    }
    return render(request, 'users/login.html', data)

def auth_user(request):
    if request.method == 'POST':
        form = SiteUserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                siteuser = SiteUser.objects.get(user=user)
                siteuser.is_online = True
                siteuser.save()
                return redirect('chat:index')
            else:
                return render(request, 'users/error.html', {'error': 'user is None'})
        return render(request, 'users/login.html', {'form':form, 'errors':form.errors})
    return render(request, 'users/error.html', {'error': 'Request method error'})

def logout_form(request):
    siteuser = SiteUser.objects.get(user=request.user)
    siteuser.is_online = False
    siteuser.save()
    logout(request)
    return redirect('users:login_form')

templates/users/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ error }}

    <br><br>
    <a href="{% url 'users:login_form' %}">Login Page</a>
</body>
</html>

templates/users/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'users/css/index.css' %}">
    <script src="{% static 'users/js/index.js' %}" defer></script>
</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-md-5 mx-auto">
            <div id="first">
                <div class="myform form ">
                    <div class="logo mb-3">
                        <div class="col-md-12 text-center">
                            <h1>Login 000</h1>
                        </div>
                    </div>
                    <form action="{% url 'users:auth_user' %}" method="post" name="login">
                        {% csrf_token %}
                        {{ form.username }}
                        {{ form.password }}
                        <br>
                        <span style="color:red;">{{ errors }}</span>
                        <div class="col-md-12 text-center ">
                            <button type="submit" class=" btn btn-block mybtn btn-primary tx-tfm">Login</button>
                            <a href="{% url 'users:register_form' %}">Go to Register Page</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/users/register.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'users/css/index.css' %}">
    <script src="{% static 'users/js/index.js' %}" defer></script>
</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-md-5 mx-auto">
            <div id="first">
                <div class="myform form ">
                    <div class="logo mb-3">
                        <div class="col-md-12 text-center">
                            <h1>Register</h1>
                        </div>
                    </div>
                    <form action="{% url 'users:adduser' %}" method="post" name="login">
                        {% csrf_token %}
                        {{ form }}
                        <br>
                        <div class="col-md-12 text-center ">
                            <button type="submit" class=" btn btn-block mybtn btn-primary tx-tfm">Register</button>
                            <a href="{% url 'users:login_form' %}">Go to Login Page</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>